
FROM ruby:3.2.9-alpine AS base

LABEL maintainer="dean@deanpcmad.com"

RUN apk add --no-cache \
    build-base \
    gcompat \
    postgresql-dev \
    sqlite-dev \
    mariadb-dev \
    git \
    bash \
    tzdata
