
FROM ruby:3.3.5-alpine AS base

LABEL maintainer="dean@deanpcmad.com"

RUN apk add --no-cache \
    build-base \
    gcompat \
    postgresql-dev \
    sqlite-dev \
    mariadb-dev \
    git \
    bash \
    tzdata \
    nodejs-current \
    npm \
    yarn
