name: Build images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - '3.1-alpine'
          - '3.1-alpine-node'
          - '3.2-alpine'
          - '3.2-alpine-node'
          - '3.3-alpine'
          - '3.3-alpine-node'
          - '3.4-alpine'
          - '3.4-alpine-node'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/deanpcmad/rails-docker:${{ matrix.version }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
